### ISSUE TITLE
`make all` does not work

### ISSUE THREAD

**Issue by phdowling** [mrlamm/textual-analogy-parsing#1]
Hi, first of all thanks for sharing this code. I'm trying to get everything to run on my machine, but after a clone of the repository, `make all` from the `src/` directory fails:
```
source .env/bin/activate
/bin/bash: .env/bin/activate: No such file or directory
Makefile:46: recipe for target 'results/neural_all.ilp.predictions.jsonl' failed
make: *** [results/neural_all.ilp.predictions.jsonl] Error 1
```

I made a few modifications, to begin with I changed the `all` rule to
```
all: install-requirements  .results
```

and  `install-requirements` to
```
install-requirements: gurobi810 .env
        source .env/bin/activate && cd gurobi810/linux64/ && python setup.py install && bin/grbgetkey $(GUROBIKEY)
        source .env/bin/activate && pip install -r ./requirements.txt
```

(and similar changes on Mac).

However, this core problem persists, and I think it's probably a simple issue with how the Makefile is structured and makes use of `%` pattern matching:
`make: *** No rule to make target `results/neural_all.ilp.predictions.jsonl', needed by `.results'.  Stop.`

Any help would be appreciated.

**Comment by arunchaganty** [comment]
Hi Phillip,
   Sorry, this was a straight up bug on our part. We had renamed the data file from "annotated_train.json" to "train.json" and hadn't updated the Makefile appropriately, causing it to fail. I've just pushed the corrected version to the repo, so I hope that it starts to work. 

Cheers!

**Comment by phdowling** [comment]
Thank @arunchaganty! I had noticed that too and changed it. I was able to run `make all` after changing my gurobi license path and manually running `make install-requirements` (which I also had to make a few small alterations to to get it to run - basically removing the `.env` target cause it was redundant). 

My local install is progressing but I still haven't been able to actually run a custom example (I tried starting in shell mode manually, but it also seems that that code is broken, there's a TODO in the code for `run_example` that suggests as much).

Another small instance where I ran into problems: I think your CoreNLP client dependency version relies on Stanford's internal CoreNLP build, it expects a run script that doesn't exist in the official release. I ended up running my own CoreNLP server and changing the featurizer's line 41 to something like:
```
self.client = CoreNLPClient(start_server=False, annotators=self.annotators.split(), properties=self.properties, endpoint="http://localhost:9012")
```
Note that self.annotators usage was also broken compared to what the official client library expects.

Let me know if this all makes sense so far, I'm not sure all of my fixes are truly fixing anything!

**Comment by phdowling** [comment]
Another follow up - scoring also still fails in the out-of-the-box setting. Training runs for a while, I see lots of output, and then this:

```
Best objective 2.723835661325e+01, best bound 2.723835661325e+01, gap 0.0000%
97it [24:04, 14.89s/it]
source .env/bin/activate && python evaluate.py -g results/neural_all.ilp.predictions.jsonl -G ../data/test.json -o results/neural_all.ilp.score
Cross-validation:   0%|                                                                                                                                                                                                                                              | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "evaluate.py", line 94, in <module>
    ARGS.func(ARGS)
  File "evaluate.py", line 55, in do_command
    ret = cross_validate(dataset, score, args.cross_validation_splits, metrics=args.metrics)
  File "evaluate.py", line 42, in cross_validate
    ret_ = fn(train, dev, **kwargs)
  File "evaluate.py", line 26, in score
    scorer.update(gold, guess)
  File "/home/ubuntu/tap2/textual-analogy-parsing/src/prosestats/evaluation.py", line 216, in update
    assert gold.tokens == guess.tokens
AssertionError
Makefile:45: recipe for target 'results/neural_all.ilp.score' failed
make: *** [results/neural_all.ilp.score] Error 1

```
